name: aiDev
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - aiohappyeyeballs=2.4.0=py310hca03da5_0
  - annotated-types=0.6.0=py310hca03da5_0
  - anyio=4.2.0=py310hca03da5_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - arrow-cpp=16.1.0=hbc20fb2_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=py310hca03da5_0
  - aws-c-auth=0.6.19=h80987f9_0
  - aws-c-cal=0.5.20=h80987f9_0
  - aws-c-common=0.8.5=h80987f9_0
  - aws-c-compression=0.2.16=h80987f9_0
  - aws-c-event-stream=0.2.15=h313beb8_0
  - aws-c-http=0.6.25=h80987f9_0
  - aws-c-io=0.13.10=h80987f9_0
  - aws-c-mqtt=0.7.13=h80987f9_0
  - aws-c-s3=0.1.51=h80987f9_0
  - aws-c-sdkutils=0.1.6=h80987f9_0
  - aws-checksums=0.1.13=h80987f9_0
  - aws-crt-cpp=0.18.16=h313beb8_0
  - aws-sdk-cpp=1.10.55=h313beb8_0
  - blas=1.0=openblas
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.3.7=py310hbda83bc_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py310h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.9.24=hca03da5_0
  - certifi=2024.8.30=py310hca03da5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py310h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datasets=2.19.1=py310hca03da5_0
  - debugpy=1.6.7=py310h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.8=py310hca03da5_0
  - distro=1.9.0=py310hca03da5_0
  - docker-pycreds=0.4.0=py_0
  - et_xmlfile=1.1.0=py310hca03da5_0
  - exceptiongroup=1.2.0=py310hca03da5_0
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.13.1=py310hca03da5_0
  - fonttools=4.51.0=py310h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - gflags=2.2.2=h313beb8_1
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.5.0=h313beb8_1
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py310h8c48613_0
  - gpytorch=1.12=pyhd8ed1ab_0
  - h11=0.14.0=py310hca03da5_0
  - httpcore=1.0.2=py310hca03da5_0
  - httpx=0.27.0=py310hca03da5_0
  - huggingface_hub=0.24.6=py310hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py310hca03da5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.25.0=py310hca03da5_0
  - jaxtyping=0.2.30=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py310hca03da5_0
  - jiter=0.6.1=py310h7a930dc_0
  - joblib=1.4.2=py310hca03da5_0
  - jpeg=9e=h80987f9_1
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hca03da5_0
  - kiwisolver=1.4.4=py310h313beb8_0
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libabseil=20240116.2=cxx17_h00cdb27_1
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcurl=8.4.0=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libgrpc=1.62.2=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=4.25.3=hbfab5d5_0
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.0=h3e2b118_0
  - libthrift=0.15.0=h73c2103_2
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxgboost=2.0.3=h313beb8_0
  - libzlib=1.2.13=hfb2fe0b_6
  - linear_operator=0.5.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py310h80987f9_0
  - matplotlib=3.9.2=py310hb6292c7_1
  - matplotlib-base=3.9.2=py310heb73f16_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py310hca03da5_0
  - multiprocess=0.70.15=py310hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - networkx=3.3=py310hca03da5_0
  - numexpr=2.8.7=py310hecc3335_0
  - numpy=1.26.4=py310h3b2db8e_0
  - numpy-base=1.26.4=py310ha9811e2_0
  - openai=1.51.2=pyhd8ed1ab_0
  - openjpeg=2.4.0=h0ed58ac_1
  - openpyxl=3.1.5=py310h80987f9_0
  - openssl=3.3.1=hfb2fe0b_2
  - orc=2.0.1=h937ddfc_0
  - packaging=24.1=py310hca03da5_0
  - pandas=2.2.2=py310h2216879_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.3.0=py310h80987f9_0
  - pip=24.0=py310hca03da5_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=py310hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py310h1e88e72_0
  - psutil=5.9.0=py310h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.0.3=cpu_pyh995e691_4
  - pyarrow=16.1.0=py310h46d7db6_0
  - pybind11-abi=5=hd3eb1b0_0
  - pydantic=2.8.2=py310hca03da5_0
  - pydantic-core=2.20.1=py310hf0e4da2_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.13=h2469fbe_1_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py310h1a28f6b_1
  - python_abi=3.10=2_cp310
  - pytorch=2.3.1=py3.10_0
  - pytz=2024.1=py310hca03da5_0
  - pyyaml=6.0.1=py310h80987f9_0
  - pyzmq=25.1.2=py310h313beb8_0
  - qhull=2020.2=h48ca7d4_2
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - regex=2024.9.11=py310h80987f9_0
  - requests=2.32.2=py310hca03da5_0
  - safetensors=0.4.4=py310h482802a_0
  - sentry-sdk=2.13.0=pyhd8ed1ab_0
  - setproctitle=1.3.3=py310h2aa6e3c_0
  - setuptools=69.5.1=py310hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.0=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py310hca03da5_0
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tk=8.6.14=h6ba3021_0
  - tokenizers=0.20.0=py310hdeb0604_0
  - torchaudio=2.3.1=py310_cpu
  - torchvision=0.18.1=py310_cpu
  - tornado=6.4.1=py310h80987f9_0
  - traitlets=5.14.3=py310hca03da5_0
  - transformers=4.45.2=pyhd8ed1ab_1
  - typeguard=2.13.3=py310hca03da5_0
  - typing-extensions=4.11.0=py310hca03da5_0
  - typing_extensions=4.11.0=py310hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - ujson=5.10.0=py310h313beb8_0
  - unicodedata2=15.1.0=py310h80987f9_0
  - urllib3=2.2.2=py310hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wandb=0.16.6=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py310hca03da5_0
  - xgboost=2.0.3=cpu_pyhb8f9a19_4
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.17.0=py310hca03da5_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.5=hd90d995_2
  - pip:
      - accelerate==1.0.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - attrs==23.2.0
      - cffi==1.17.1
      - colorlog==6.8.2
      - cryptography==43.0.3
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - mako==1.3.5
      - multidict==6.0.5
      - optuna==3.6.1
      - pdfminer==20191125
      - pdfminer-six==20240706
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pyparsing==3.1.2
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - sqlalchemy==2.0.32
      - torch-cluster==1.6.3
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - tqdm==4.66.4
      - yarl==1.9.4
prefix: /opt/miniconda3/envs/aiDev
